apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonflask-app
  labels:
    app: pythonflask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonflask
  template:
    metadata:
      labels:
        app: pythonflask
    spec:
      containers:
      - name: pythonflask
        image: yenaing/python_flask
        ports:
        - containerPort: 5000
        securityContext:
          privileged: true
        volumeMounts:
        - name: hostvol
          mountPath: /opt
      volumes:
        - name: hostvol
          persistentVolumeClaim:
            # PVC name you created
            claimName: pythonflask-pvc
